// src/coaches.js
export const coaches = {
  "1": "Javier Aguirre",
  "2": "Hugo Broos",
  "3": "Hong Myung-bo",
  "4": "Miroslav Koubek",
  "5": "Jesse Marsch",
  "6": "Sergej Barbarez",
  "7": "Julen Lopetegui",
  "8": "Murat Yakin",
  "9": "Carlo Ancelotti",
  "10": "Mohamed Ouahbi",
  "11": "Sébastien Migné",
  "12": "Steve Clarke",
  "13": "Mauricio Pochettino",
  "14": "Gustavo Alfaro",
  "15": "Tony Popovic",
  "16": "Vincenzo Montella",
  "17": "Julian Nagelsmann",
  "18": "Dick Advocaat",
  "19": "Emerse Faé",
  "20": "Sebastián Beccacece",
  "21": "Ronald Koeman",
  "22": "Hajime Moriyasu",
  "23": "Graham Potter",
  "24": "Sabri Lamouchi",
  "25": "Rudi García",
  "26": "Hossam Hassan",
  "27": "Amir Ghalenoei",
  "28": "Darren Bazeley",
  "29": "Luis de la Fuente",
  "30": "Pedro Leitão Brito",
  "31": "Georgios Donis",
  "32": "Marcelo Bielsa",
  "33": "Didier Deschamps",
  "34": "Pape Thiaw",
  "35": "Graham Arnold",
  "36": "Ståle Solbakken",
  "37": "Lionel Scaloni",
  "38": "Vladimir Petković",
  "39": "Ralf Rangnick",
  "40": "Jamal Sellami",
  "41": "Roberto Martínez",
  "42": "Sébastien Desabre",
  "43": "Fabio Cannavaro",
  "44": "Néstor Lorenzo",
  "45": "Thomas Tuchel",
  "46": "Zlatko Dalić",
  "47": "Carlos Queiroz",
  "48": "Thomas Christiansen"
};