// src/teamsData.js
export const teams = {
  "1": { name: "México", flag: "https://flagcdn.com/w80/mx.png" },
  "2": { name: "South Africa", flag: "https://flagcdn.com/w80/za.png" },
  "3": { name: "South Korea", flag: "https://flagcdn.com/w80/kr.png" },
  "4": { name: "Czech Republic", flag: "https://flagcdn.com/w80/cz.png" },
  "5": { name: "Canada", flag: "https://flagcdn.com/w80/ca.png" },
  "6": { name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w80/ba.png" },
  "7": { name: "Qatar", flag: "https://flagcdn.com/w80/qa.png" },
  "8": { name: "Switzerland", flag: "https://flagcdn.com/w80/ch.png" },
  "9": { name: "Brazil", flag: "https://flagcdn.com/w80/br.png" },
  "10": { name: "Morocco", flag: "https://flagcdn.com/w80/ma.png" },
  "11": { name: "Haiti", flag: "https://flagcdn.com/w80/ht.png" },
  "12": { name: "Scotland", flag: "https://flagcdn.com/w80/gb-sct.png" },
  "13": { name: "United States", flag: "https://flagcdn.com/w80/us.png" },
  "14": { name: "Paraguay", flag: "https://flagcdn.com/w80/py.png" },
  "15": { name: "Australia", flag: "https://flagcdn.com/w80/au.png" },
  "16": { name: "Turkey", flag: "https://flagcdn.com/w80/tr.png" },
  "17": { name: "Germany", flag: "https://flagcdn.com/w80/de.png" },
  "18": { name: "Curaçao", flag: "https://flagcdn.com/w80/cw.png" },
  "19": { name: "Ivory Coast", flag: "https://flagcdn.com/w80/ci.png" },
  "20": { name: "Ecuador", flag: "https://flagcdn.com/w80/ec.png" },
  "21": { name: "Netherlands", flag: "https://flagcdn.com/w80/nl.png" },
  "22": { name: "Japan", flag: "https://flagcdn.com/w80/jp.png" },
  "23": { name: "Sweden", flag: "https://flagcdn.com/w80/se.png" },
  "24": { name: "Tunisia", flag: "https://flagcdn.com/w80/tn.png" },
  "25": { name: "Belgium", flag: "https://flagcdn.com/w80/be.png" },
  "26": { name: "Egypt", flag: "https://flagcdn.com/w80/eg.png" },
  "27": { name: "Iran", flag: "https://flagcdn.com/w80/ir.png" },
  "28": { name: "New Zealand", flag: "https://flagcdn.com/w80/nz.png" },
  "29": { name: "Spain", flag: "https://flagcdn.com/w80/es.png" },
  "30": { name: "Cape Verde", flag: "https://flagcdn.com/w80/cv.png" },
  "31": { name: "Saudi Arabia", flag: "https://flagcdn.com/w80/sa.png" },
  "32": { name: "Uruguay", flag: "https://flagcdn.com/w80/uy.png" },
  "33": { name: "France", flag: "https://flagcdn.com/w80/fr.png" },
  "34": { name: "Senegal", flag: "https://flagcdn.com/w80/sn.png" },
  "35": { name: "Iraq", flag: "https://flagcdn.com/w80/iq.png" },
  "36": { name: "Norway", flag: "https://flagcdn.com/w80/no.png" },
  "37": { name: "Argentina", flag: "https://flagcdn.com/w80/ar.png" },
  "38": { name: "Algeria", flag: "https://flagcdn.com/w80/dz.png" },
  "39": { name: "Austria", flag: "https://flagcdn.com/w80/at.png" },
  "40": { name: "Jordan", flag: "https://flagcdn.com/w80/jo.png" },
  "41": { name: "Portugal", flag: "https://flagcdn.com/w80/pt.png" },
  "42": { name: "DR Congo", flag: "https://flagcdn.com/w80/cd.png" },
  "43": { name: "Uzbekistan", flag: "https://flagcdn.com/w80/uz.png" },
  "44": { name: "Colombia", flag: "https://flagcdn.com/w80/co.png" },
  "45": { name: "England", flag: "https://flagcdn.com/w80/gb-eng.png" },
  "46": { name: "Croatia", flag: "https://flagcdn.com/w80/hr.png" },
  "47": { name: "Ghana", flag: "https://flagcdn.com/w80/gh.png" },
  "48": { name: "Panama", flag: "https://flagcdn.com/w80/pa.png" }
};